# -*- coding: utf-8 -*-
"""Collect FAQs related to a topic or product (questions and their answers).

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHmBhwAq8f03Sn9pWmVKxAuM63Y8Lmld
"""

# Chatbot for FAQs using a rule-based approach

# Step 1: Define FAQ data (you can expand this list)
faq_data = {
    "what is your return policy": "Our return policy allows returns within 30 days of purchase.",
    "how long does shipping take": "Shipping usually takes 3-5 business days.",
    "how can I track my order": "You can track your order using the tracking link sent to your email.",
    "do you ship internationally": "Yes, we ship to most countries worldwide.",
    "what payment methods are accepted": "We accept credit cards, debit cards, and PayPal.",
    "how can I contact customer support": "You can contact support at support@example.com.",
}

# Step 2: Function to find best match
def get_answer(user_question):
    user_question = user_question.lower().strip()

    for question in faq_data:
        if user_question in question or question in user_question:
            return faq_data[question]

    return "Sorry, I couldn't find an answer to your question."

# Step 3: Chat loop
print("Welcome to the FAQ Chatbot! Type 'exit' to stop.")

while True:
    user_input = input("\nYou: ")
    if user_input.lower() == "exit":
        print("Chatbot: Thank you! Have a great day.")
        break

    response = get_answer(user_input)
    print("Chatbot:", response)