# -*- coding: utf-8 -*-
"""Display the best matching answer as a chatbot response.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPNy8IpNmIEupfqUbQUT_hBTcIs4dkwb
"""

# Install required library
!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer, util

# Sample QA database
qa_data = {
    "how to reset my password": "To reset your password, click on 'Forgot Password' on the login page.",
    "how to contact support": "You can contact support at support@example.com.",
    "what are the working hours": "Our working hours are from 9 AM to 6 PM, Monday to Friday.",
    "how to delete my account": "Please email delete@example.com to request account deletion.",
    "how to update my profile": "Go to account settings and click 'Edit Profile'."
}

questions = list(qa_data.keys())
answers = list(qa_data.values())

model = SentenceTransformer('all-MiniLM-L6-v2')
question_embeddings = model.encode(questions)

print("Welcome to the Help Chatbot. Type your question or 'exit' to stop.\n")

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Bot: Thank you. Have a nice day.")
        break
    user_embedding = model.encode(user_input)
    similarity_scores = util.cos_sim(user_embedding, question_embeddings)[0]
    best_index = similarity_scores.argmax()
    print("Bot:", answers[best_index])