# -*- coding: utf-8 -*-
"""Match user questions with the most similar FAQ using techniques like cosine similarity or intent  matching.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDlYV3SFP-zl_amjDwQtOFswWMiMAVEp
"""

# Install required library
!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer, util

faqs = {
    "how can I apply for admission": "You can apply for admission through our online application portal.",
    "what documents are required for admission": "You need to submit your 10th and 12th mark sheets, ID proof, and passport size photos.",
    "is there any entrance exam": "Yes, you need to appear for our university entrance exam to qualify.",
    "what is the last date to apply": "The last date to apply is July 15th.",
    "what is the application fee": "The application fee is Rs. 500 and can be paid online.",
    "how can I contact the admission office": "You can contact the admission office at admission@college.edu or call +91-9876543210."
}

questions = list(faqs.keys())
answers = list(faqs.values())

model = SentenceTransformer('all-MiniLM-L6-v2')
faq_embeddings = model.encode(questions)

print("Welcome to the Admission FAQ Bot. Type 'exit' to quit.\n")

while True:
    user_input = input("You: ")
    if user_input.lower() == 'exit':
        print("Bot: Thank you and goodbye.")
        break
    user_embedding = model.encode(user_input)
    similarity_scores = util.cos_sim(user_embedding, faq_embeddings)[0]
    best_index = similarity_scores.argmax()
    print("Bot:", answers[best_index])