# -*- coding: utf-8 -*-
"""Optional: Create a simple chat UI for user interaction.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-od7qvG5c-4heZZoid_1DQMwQGrXq_O
"""

!pip install -q sentence-transformers gradio

from sentence_transformers import SentenceTransformer, util
import gradio as gr

faqs = {
    "how can I check my exam results": "Visit the results portal and log in using your student ID.",
    "when will the semester results be declared": "Semester results will be declared within 30 days after exams.",
    "how can I apply for revaluation": "You can apply for revaluation through the student dashboard.",
    "what if I fail in an exam": "You can appear for the supplementary exam scheduled next semester.",
    "how can I download my marksheet": "Marksheet can be downloaded from the results section in your profile."
}

questions = list(faqs.keys())
answers = list(faqs.values())

model = SentenceTransformer("all-MiniLM-L6-v2")
faq_embeddings = model.encode(questions)

def chatbot_response(user_input):
    if user_input.strip() == "":
        return "Please enter a question."
    user_embedding = model.encode(user_input)
    similarity_scores = util.cos_sim(user_embedding, faq_embeddings)[0]
    best_index = similarity_scores.argmax()
    return answers[best_index]

iface = gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(placeholder="Ask about exams or results..."),
    outputs="text",
    title="Student Exam Help Chatbot",
    description="Ask any question related to your exams or results."
)

iface.launch()